connection:
    url: https://rally1.rallydev.com/slm/webservice/v2.0
    schema_url: https://rally1.rallydev.com/slm/schema/v2.0/workspace/56371159504
    user: nick@denver.com
    password: P@$$w0rd
    endpoint: workitem
    witype: hierarchicalrequirement
    
params:
    workspace: 56371159504
    pagesize: 200
    start: 1
    query: ''
    fetch: CreationDate,ObjectID,State,PlanEstimate,ScheduleState
    
db:
    name: rally
    user: postgres
    password: postgres
    host: 127.0.0.1
    port: 5432
    tables: Defect, HierarchicalRequirement
    