ac:
    url:       rally1.rallydev.com
    user:      user@co.com
    password:  secret
    apikey  :  _AbC123
    workspace: W1
    project:   P1
    query: LastUpdateDate >= 2015-06-01
    fetch: CreationDate,ObjectID,ScheduleState,PlanEstimate,State,Severity,FixedInBuild,c_Musketeer,c_AliasesOfMilady

db:
    name: rally
    user: postgres
    password: postgres
    host: 127.0.0.1
    port: 5432
    tables: Defect, HierarchicalRequirement
    